title: HFS - CCQC
email: ccq@uga.edu
description: >
  Research group website for Henry F. Schaefer III, director of the 
  Center of Computational Quantum Chemistry, a part of the
  Department of Chemistry at the University of Georgia. 
tagline: All Quantum, All the Time

baseurl: "" 
url: https://ccqc.github.io
author: CCQC
github_username:  CCQC
project_repository: ccqc.github.io

permalink: pretty
favicon: /img/icons/favicon.png
theme_color: '#b02b21'
footer_menu: footer_menu.yml
logo: /img/ccqc_logo.png

twitter:
  username: CCQC_UGA
  card: summary
social:
  name:
  links:
    - https://twitter.com/ccqc_uga?lang=en
    - https://www.facebook.com/pages/Center-for-Computational-Quantum-Chemistry/107917969264397
    - https://www.instagram.com/ccqc_at_uga/?igshid=NTc4MTIwNjQ2YQ%3D%3D
    - https://github.com/CCQC

defaults:
  - scope:
      path: ""
    values:
      image: /img/ccqc_logo.png
      author: CCQC

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - kramdown-parser-gfm

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
